- 👋 Hi, I’m @vimray009
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Raymond Havim : Hi I am Raymond, a Student of Software Engineering(ALX), Cloud Engineering and Data Science.
--->
